name: Publish

on:
  release:
    types: [published]

jobs:
  prepare:
    name: Cleanup existing workflows
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
  deploy:
    uses: ./.github/workflows/_deploy_to_surge.yaml
    secrets: inherit
    with:
      environment: production
      SURGE_DOMAIN: simplecommerce.surge.sh